font:
  normal:
    family: Hasklug Nerd Font Mono
    style: Regular
  bold:
    family: Hasklug Nerd Font Mono
    style: Bold
  italic:
    family: Hasklug Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hasklug Nerd Font Mono
    style: Bold Italic

colors:
  primary:
    background: '#0f111b'
    foreground: '#ecf0c1'

  normal:
    black:   '#000000'
    red:     '#e33400'
    green:   '#5ccc96'
    yellow:  '#f2ce00'
    blue:    '#00a3cc'
    magenta: '#b3a1e6'
    cyan:    '#7a5ccc'
    white:   '#686f9a'
